### ISSUE TITLE
style.scss render fails if site.Menus is empty / unconfigured

### ISSUE THREAD

**Issue by dmorn** [yawpitchroll/frugal#1]
### Context
I just created an empty Hugo project and added the theme as a submodule, set the "theme" property of my "config.toml" file, and run:
```
$ hugo server -D
Building sites … WARNING: calling IsSet with unsupported type "invalid" (<nil>) will always return false.

ERROR 2019/08/06 19:38:31 error: failed to transform resource: template: scss/style.scss:746:23: executing "scss/style.scss" at <len site.Menus.main>: error calling len: len of untyped nil
Total in 41 ms
Error: Error building site: logged 1 error(s)
```
#### Expected behaviour
I would expect that the site builds without problems.

#### Suggestions
Maybe [this issue](https://github.com/EmielH/tale-hugo/issues/2) might be helpful!

**Comment by yawpitch** [comment]
Hmm, I'm pretty sure I included the pre-rendered css files [here](https://github.com/yawpitchroll/frugal/tree/master/resources/_gen/assets/scss).

I _think_ this might be an error because you don't have any menu items configured. Try copying in the exampleSite/config.toml and see if you can generate build the site.

There's some logic in the style.scss that tries to figure out a height via the number of menu items it will need to stack and with no menu items configured it's erroring.

I'll try to fix that soon, but configuring a menu _should_ get you going.

**Comment by dmorn** [comment]
Nice catch thank you @yawpitch, the workaround works 👍 I'll let you close the issue, in case that you want to change the title and refer to it for the "height problem". Cheers

**Comment by yawpitch** [comment]
Thanks, glad it's working for you. I'll change the title and come back to it in a couple of days. Pretty sure I just need to set a default for the case of no menus. Thanks for the catch!

**Comment by yawpitch** [comment]
@jecoz I _think_ this should be fixed; for some reason I couldn't easily recreate it on my machine.
